# Generated by Django 2.2.4 on 2023-06-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0002_auto_20230616_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='relaese_date',
            field=models.DateTimeField(null=True),
        ),
    ]
