# Generated by Django 2.2.4 on 2023-06-16 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0003_auto_20230616_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='relaese_date',
        ),
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 16, 12, 53, 52, 574523, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
