# Generated by Django 2.2.4 on 2023-06-16 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0005_remove_show_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 16, 12, 58, 8, 801619, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
