# Generated by Django 2.2.4 on 2023-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pages',
            field=models.TextField(default=1200),
            preserve_default=False,
        ),
    ]
