# Generated by Django 2.2.4 on 2023-06-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20230619_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('text', models.TextField()),
                ('desc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses_app.Course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
