# Generated by Django 2.2.4 on 2023-06-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='release_date',
        ),
    ]
