# Generated by Django 2.2.4 on 2023-07-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='users',
            new_name='user',
        ),
    ]
